test:
  image: conda/miniconda3
  script:
    - conda install openbabel
    - conda install -c bioconda autodock-vina
    - conda config --add channels conda-forge
    - conda install rdkit cython
    - pip install -e .
    - pytest
