test:
  image: conda/miniconda3
  script:
    - conda install -y -c conda-forge openbabel
    - conda install -y -c bioconda autodock-vina
    - conda install -y -c conda-forge rdkit cython
    - pip install -e .
    - pytest
