variables:
  IMAGE_PATH: "${CI_REGISTRY_IMAGE}/default:${CI_COMMIT_REF_SLUG}"

stages:
  - build-image
  - test

build-image:
  before_script:
    - docker login -u gitlab-ci-token -p ${CI_JOB_TOKEN} ${CI_REGISTRY}
  script:
    - docker build --no-cache -t "${IMAGE_PATH}" .
    - docker push "${IMAGE_PATH}"
  tags:
    - docker
  when: manual
  stage: build-image

test:
  image: "${IMAGE_PATH}"
  script:
    - source ~/.anaconda/bin/activate && conda activate lead
    - pip install -e .
    - pytest
  stage: test
