path_classifiers:
    # include test files in analysis
    test:
        - exclude: tests
    docs:
        - docs
    notebooks:
        - notebooks
extraction:
    python:
        index:
            exclude:
                - moldrug/_version.py
                - versioneer.py