path_classifiers:
    test:
        - tests
    docs:
        - docs
extraction:
    python:
        index:
            exclude:
                - moldrug/_version.py
                - moldrug/CustomMolDrugFitness.py