name: moldrug
channels:
  - conda-forge
dependencies:
  - pip
  - python==3.9.*
  - rdkit
  - conda-build
  - pip:
    - opencv-python-headless
    - moldrug
    - mols2grid
    - prolif
    - streamlit