{% set version = "0.0.1.beta8" %}

package:
  name: moldrug
  version: {{ version }}

source:
  url: https://github.com/ale94mleon/MolDrug/archive/refs/tags/{{ version }}.tar.gz
  sha256: 012eb5fe250493ead4aeeb9f7cd795830710d25ee0ac5e0d78f08a9b0b37c9dd

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python
    - pip
  run:
    - rdkit 2022.*.*
    - openbabel 3.1.0
    - autodock-vina
    - python
    - pyyaml
    - ipykernel
    - ipython

test:
  imports:
    - moldrug

about:
  home: https://github.com/ale94mleon/MolDrug
  license:  Apache-2.0 license
  summary: 'An in silico tool for the lead generation and optimization on the drug design phase'
  dev_url: https://github.com/ale94mleon/MolDrug
  doc_url: https://moldrug.readthedocs.io/en/latest/
  doc_source_url: https://github.com/ale94mleon/MolDrug/tree/main/docs/source
