{% set version = "0.0.1.beta7" %}

package:
  name: moldrug
  version: {{ version }}

source:
  url: https://github.com/ale94mleon/MolDrug/archive/refs/tags/{{ version }}.tar.gz
#  sha256: a79e213a49851ead961e266d7eac106e84ff89c9562f4b52be938d90cedbb861

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python
    - pip
  run:
    - rdkit 2022.*.*
    - openbabel 3.1.0
    - autodock-vina
    - python

test:
  imports:
    - moldrug

about:
  home: https://github.com/ale94mleon/MolDrug
  license:  Apache-2.0 license
  summary: 'From molecule to drug'
  dev_url: https://github.com/ale94mleon/MolDrug
  doc_url: https://github.com/ale94mleon/MolDrug
  doc_source_url: https://github.com/ale94mleon/MolDrug/blob/main/README.rst
