name: moldrug
channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - ipykernel
  - ipython
  - ipywidgets
  - pip
  - python==3.9.*
  - rdkit
  - nbsphinx
  - sphinx==5.3.0
  - tqdm
  - vina
  - conda-build
  - pip:
    - numpy
    - pandas
    - pyyaml
    - meeko
    - scipy
    - six
    - crem
    - requests
    - pytest
    - recommonmark
    - sphinx_copybutton
    - myst_nb
    - recommonmark
    - sphinx_book_theme