# coding: utf-8
# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = '0.0.1b9.dev13+g6419be2.d20220714'
__version_tuple__ = version_tuple = (0, 0, 1, 'dev13', 'g6419be2.d20220714')
