name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-20.04
    # strategy:
    #   max-parallel: 5

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python3.10.4
      uses: actions/setup-python@v3
      with:
        python-version: 3.10.4
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    - name: Install dependencies
      run: |
        conda env update --file environment.yml --name base
    - name: Lint with flake8
      run: |
        conda install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Install conda dependencies
      run: |
        conda install -y -c conda-forge rdkit">=2022.0"
        conda install -y -c conda-forge openbabel">=3.1.0"
        conda install -y -c bioconda autodock-vina
    - name: Install conda dependencies
      run: |
        pip install -e .[dev]
    - name: Test with pytest
      run: |
        pytest
