name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-20.04
    # strategy:
    #   max-parallel: 5

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python3.10.4
      uses: actions/setup-python@v3
      with:
        python-version: 3.10.4
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    - name: Create lead env
      run: |
        conda init bash
        conda create -n lead -y
    - name: Install dependencies
      run: |
        conda activate lead
        conda install -y -c conda-forge rdkit">=2022.0"
        conda install -y -c conda-forge openbabel">=3.1.0"
        conda install -y -c bioconda autodock-vina
    - name: Install lead on developer mode
      run: |
        conda activate lead
        pip install -e .[dev]
    - name: Test with pytest
      run: |
        conda activate lead
        pytest
